require('myplugins/lsp')
require('myplugins/chadtree')
require('myplugins/nvim-treesitter')
require('myplugins/lspkind')
require('myplugins/nvim-cmp')
require('myplugins/lualine')
require('myplugins/devicons')
require('myplugins/autopairs')
require('myplugins/ts-autotag')
require('myplugins/nvim-test')
-- require('myplugins/obsidian')
require('myplugins/zk')
require("myplugins/comment")
